name: .NET + Testcontainers

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

env:
  TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"
  TESTCONTAINERS_RYUK_DISABLED: "true"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Check Docker access
      run: docker info

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests with Testcontainers
      run: |
        mkdir -p TestResults
        dotnet test --no-build --verbosity normal \
          --logger "trx;LogFileName=TestResults/results.trx"

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults/
