name: .NET with Testcontainers

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    # Activer Docker in Docker en mode privilégié
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
      options: --privileged

    services:
      docker:
        image: docker:dind
        ports:
          - 2375:2375
        options: >-
          --dns 8.8.8.8
          --name dind
          --entrypoint dockerd-entrypoint.sh

    steps:
    - uses: actions/checkout@v4

    - name: Install Docker CLI inside container
      run: |
        apt-get update
        apt-get install -y docker.io
        dockerd & sleep 10
        docker version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore

    - name: Run tests (Testcontainers ready)
      run: |
        mkdir -p TestResults
        dotnet test --no-build --verbosity normal \
          --logger "trx;LogFileName=TestResults/results.trx"

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults/
