name: .NET with Testcontainers

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Ajout du Docker daemon (nécessaire à Testcontainers)
    steps:
    - name: Set up Docker (start Docker daemon)
      uses: docker/setup-buildx-action@v3

    - uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Ensure Docker is running
      run: docker info

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore

    - name: Run tests with Testcontainers
      run: |
        mkdir -p TestResults
        dotnet test --no-build --verbosity normal \
          --logger "trx;LogFileName=TestResults/results.trx"

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults/
