name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:   # Déclenchement manuel

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Check Docker version
        run: docker --version
      
      - name: Start Docker
        run: sudo service docker start

      - name: Fix apt sources and install LDAP libs
        run: |
          sudo sed -i 's/^# deb/deb/' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y libldap-2.4-2 libsasl2-2 libsasl2-modules

      - name: Create certs folder for docker mount
        run: mkdir -p ./Ldap.Test/bin/Release/net8.0/certs
      
      - name: Copy certs to build folder
        run: cp -r ./Ldap.Test/Certs/* ./Ldap.Test/bin/Release/net8.0/certs/  

      - name: Run tests
        run: dotnet test --configuration Release
