name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:   # Déclenchement manuel ajouté ici

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      
      - name: Restore dependencies
        run: dotnet restore ./Ldap.Test.sln
      
      - name: Build solution
        run: dotnet build ./Ldap.Test.sln --no-restore --configuration Release

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      
      - name: Restore dependencies
        run: dotnet restore ./Ldap.test
      
      - name: Build tests
        run: dotnet build ./Ldap.test --no-restore --configuration Release
      
      - name: Run tests
        run: dotnet test ./Ldap.test --no-build --verbosity normal --configuration Release
