name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install native LDAP libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libldap-2.5-0 || sudo apt-get install -y libldap-2.4-2
          sudo apt-get install -y libsasl2-2 libssl3 libkrb5-3 libldap-common
          ldconfig -p | grep ldap
          ls -l /usr/lib/x86_64-linux-gnu/libldap*
      - name: Symlink libldap if version mismatch
        run: |
          if [ ! -f /usr/lib/x86_64-linux-gnu/libldap-2.5.so.0 ] && [ -f /usr/lib/x86_64-linux-gnu/libldap-2.4.so.2 ]; then
            sudo ln -s /usr/lib/x86_64-linux-gnu/libldap-2.4.so.2 /usr/lib/x86_64-linux-gnu/libldap-2.5.so.0
          fi


      - name: Check Docker version
        run: docker --version

      - name: Start Docker
        run: sudo service docker start

      - name: Create certs folder for docker mount
        run: mkdir -p ./Ldap.Test/bin/Release/net8.0/certs

      - name: Copy certs to build folder
        run: cp -r ./Ldap.Test/Certs/* ./Ldap.Test/bin/Release/net8.0/certs/

      - name: Run tests
        run: dotnet test --configuration Release
