name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:   # Déclenchement manuel ajouté ici

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Check Docker version
        run: docker --version
      - name: Start Docker
        run: sudo service docker start          
      - name: Run tests
        run: dotnet test --configuration Release
