name: Build Docker on Windows

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'
      - 'main'

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Check Docker version
      shell: pwsh
      continue-on-error: true
      run: docker version
      
    - name: Install Chocolatey (if not installed)
      shell: powershell
      run: |
        if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        }

    - name: Install Docker Desktop
      shell: powershell
      run: choco install docker-desktop -y

    - name: Start Docker Desktop
      shell: powershell
      run: |
        Start-Process 'C:\Program Files\Docker\Docker\Docker Desktop.exe'
        Start-Sleep -Seconds 30

    - name: Check Docker version
      shell: pwsh
      run: docker version
